apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k8s
configMapGenerator:
  - name: flappy-bird-content
    files:
      - games/flappy-bird/index.html
  - name: pong-content
    files:
      - games/pong/index.html
generatorOptions:
  disableNameSuffixHash: true
