apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minigames
resources:
  - k8s
  - namespace.yaml
configMapGenerator:
  - name: flappy-bird-content
    files:
      - games/flappy-bird/index.html
  - name: memory-content
    files:
      - games/memory/index.html
  - name: pong-content
    files:
      - games/pong/index.html
  - name: snake-content
    files:
      - games/snake/index.html
  - name: soccer-content
    files:
      - games/soccer/index.html
  - name: flappy-score-api-code
    files:
      - backend/score-api/server.js
  - name: soccer-rt-code
    files:
      - backend/soccer-rt/server.js
generatorOptions:
  disableNameSuffixHash: true
