apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minigames
resources:
  - k8s
  - namespace.yaml
configMapGenerator:
  - name: flappy-bird-content
    files:
      - games/flappy-bird/index.html
  - name: memory-content
    files:
      - games/memory/index.html
      - assets/ck_astroworld.png=games/memory/assets/ck_astroworld.png
      - assets/ck_avangers.png=games/memory/assets/ck_avangers.png
      - assets/ck_diddy.png=games/memory/assets/ck_diddy.png
      - assets/ck_dream.png=games/memory/assets/ck_dream.png
      - assets/ck_georgeFloyd.png=games/memory/assets/ck_georgeFloyd.png
      - assets/ck_ishowspeed.png=games/memory/assets/ck_ishowspeed.png
      - assets/ck_shag.png=games/memory/assets/ck_shag.png
      - assets/ck_teacher.png=games/memory/assets/ck_teacher.png
      - assets/ck_weAreCharlieKirk.png=games/memory/assets/ck_weAreCharlieKirk.png
      - assets/ck_woman.png=games/memory/assets/ck_woman.png
  - name: pong-content
    files:
      - games/pong/index.html
  - name: snake-content
    files:
      - games/snake/index.html
  - name: flappy-score-api-code
    files:
      - backend/score-api/server.js
generatorOptions:
  disableNameSuffixHash: true
