apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minigames
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: minigames-strip@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: minigames.fritz.box
      http:
        paths:
          - path: /flappy
            pathType: Prefix
            backend:
              service:
                name: flappy-bird
                port:
                  number: 80
          - path: /pong
            pathType: Prefix
            backend:
              service:
                name: pong
                port:
                  number: 80
