apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minigames
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: minigames-minigames-strip@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: raspberrypi.fritz.box
      http:
        paths:
          - path: /flappy
            pathType: Prefix
            backend:
              service:
                name: flappy-bird
                port:
                  number: 80
          - path: /memory
            pathType: Prefix
            backend:
              service:
                name: memory
                port:
                  number: 80
          - path: /pong
            pathType: Prefix
            backend:
              service:
                name: pong
                port:
                  number: 80
          - path: /snake
            pathType: Prefix
            backend:
              service:
                name: snake
                port:
                  number: 80
          - path: /soccer-ws
            pathType: Prefix
            backend:
              service:
                name: soccer-rt
                port:
                  number: 80
          - path: /soccer
            pathType: Prefix
            backend:
              service:
                name: soccer
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: flappy-score-api
                port:
                  number: 80
