apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake
  template:
    metadata:
      labels:
        app: snake
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: site-content
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: site-content
          configMap:
            name: snake-content
