apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory
  template:
    metadata:
      labels:
        app: memory
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: site-content
              mountPath: /usr/share/nginx/html
              readOnly: true
            - name: meme-assets
              mountPath: /usr/share/nginx/html/assets
              readOnly: true
      volumes:
        - name: site-content
          configMap:
            name: memory-content
        - name: meme-assets
          hostPath:
            path: /home/kale/Workspaces/kubernetes-minigames/games/memory/assets
            type: Directory
